## Часть 1

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

a) $AB$ число столбцов матрицы А не равно числу строк матрицы В, перемножить нельзя.  
$BA$ - аналогично

б) размерность $AB$ - $2\times 3$  
$BA$ перемножіть нельзя

в) $AB$ - $8\times 8$  
$BA$ - $3\times 3$

г) матрицы квадратные, размерность $AB$ и $BA$ - $4\times 4$

__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

In [15]:
import numpy as np
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])
a + b

array([[ 5, -3],
       [ 3,  5]])

In [16]:
a.dot(b)

array([[  4, -11],
       [ 12,  -3]])

In [17]:
a @ b #same

array([[  4, -11],
       [ 12,  -3]])

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [18]:
a = np.array([[1, 7], [3, -6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2, -4], [1, 1]])
3 * a + (-2) * b + 4 * c


array([[ 11,  -5],
       [  9, -12]])

__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$

In [19]:
A = np.array([[4, 1], [5, -2], [2, 3]])
A.T

array([[ 4,  5,  2],
       [ 1, -2,  3]])

In [20]:
np.dot(A, A.T)


array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [21]:
np.dot(A.T, A)

array([[45,  0],
       [ 0, 14]])

__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [24]:
"""Класс для операций сложения и умножения матриц"""
class Matrix:
    def __init__(self, matrix):
            self.matrix= matrix
    def __str__(self):
        return ','.join(map(str, self.matrix)).replace(']', '\n').replace('[', '').replace(',', '')
    def __add__(self, other):
        if len(self.matrix) == len(other.matrix):
            for row1, row2 in zip(self.matrix, other.matrix):
                if len(row1) != len(row2):
                    return f'Количество столбцов не равно, эти матрицы нельзя сложить'
            result = [[a + b for a, b in zip(row1, row2)] for row1, row2 in zip(self.matrix, other.matrix)]
            return ','.join(map(str, result)).replace(']', '\n').replace('[', '').replace(',', '')
        else:
            return f'Количество строк не равно, эти матрицы нельзя сложить'
    def __mul__(self, other):
        result = []
        try:
            for row in self.matrix:
                row_result = []
                for i in range(len(other.matrix[0])):
                    num = 0
                    for idx, el in enumerate(row):
                        num += (el * other.matrix[idx][i])
                    row_result.append(num)
                result.append(row_result)
            return ','.join(map(str, result)).replace(']', '\n').replace('[', '').replace(',', '')
        except:
            return f'Умножение матриц данной размерности невозможно'


In [25]:
m_1 = Matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
m_2 = Matrix([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(m_1)
print(m_2)
print(m_1 + m_2)

1 2 3
4 5 6
7 8 9

10 20 30
40 50 60
70 80 90

11 22 33
44 55 66
77 88 99



In [26]:
m_3 = Matrix([[4, 1], [5, -2], [2, 3]])
m_4 = Matrix([[ 4, 5, 2], [ 1, -2, 3]])
print(m_1 * m_2)
print(m_3 * m_4)
print(m_4 * m_3)

300 360 420
660 810 960
1020 1260 1500

17 18 11
18 29 4
11 4 13

45 0
0 14



In [27]:
#проверка работы класса
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
np.dot(a, b)


array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [28]:
np.dot(A, A.T)

array([[17, 18, 11],
       [18, 29,  4],
       [11,  4, 13]])

In [29]:
np.dot(A.T, A)


array([[45,  0],
       [ 0, 14]])

## Часть 2

__1.__ Вычислить определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


a) = $sin^{2}x+cos^{2}x=1$

б) = 4∗(5∗9−1∗0)−2(0∗9−1∗0)+3 (0∗0−5∗0)=4∗45=180

In [31]:
b = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
np.linalg.det(b)


180.0

в) = 1∗(5∗9−6∗8)−2∗( 4∗9−7∗6)+3∗( 4∗8−5∗7)=0


In [32]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
round(np.linalg.det(c), 2)


-0.0

__2.__ Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

а) det(AB) = detA*detB

Ответ: 4*4=16

$б)$  
$detA^{T}=detA$

Ответ: 4

в)  
Умножение строки или столбца матрицы на число λ приведёт к умножению определителя матрицы на то же число.
Таким образом, если каждая строка увеличится в 2 раза, определитель всей матрицы увеличится в $2^{n}$ раз, где n - количество строк

det(2A) = $2^{n}$ * det(A)

__3.__  Доказать, что матрица

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Матрица является вырожденной если ее определитель равен нулю.  


In [33]:
f = np.array([[-2, 7, -3], [4, -14, 6],[-3, 7, 13]])
np.linalg.det(f)

0.0

### Так как вторая строка матрицы равна первой строке умноженной на -2, то эти две строки линейно зависимы, соответственно определитель матрицы равен нулю, что и означает что матрица вырожденная

__4.__ Найти ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

In [34]:
#a) 
a = np.array([[1, 2, 3], [1, 1, 1],[2, 3, 4]])
np.linalg.matrix_rank(a)

2

In [35]:
#б) 
a = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
np.linalg.matrix_rank(a)

3